// const districts = [
//     { id: 15, name: "Agar Malwa" },
//     { id: 2, name: "Alirajpur" },
//     { id: 3, name: "Anuppur" },
//     { id: 4, name: "Ashoknagar" },
//     { id: 5, name: "Balaghat" },
//     { id: 6, name: "Barwani" },
//     { id: 7, name: "Betul" },
//     { id: 8, name: "Bhind" },
//     { id: 9, name: "Bhopal" },
//     { id: 10, name: "Burhanpur" },
//     { id: 11, name: "Chhatarpur" },
//     { id: 12, name: "Chhindwara" },
//     { id: 13, name: "Damoh" },
//     { id: 14, name: "Datia" },
//     { id: 1, name: "Dewas" },
//     { id: 16, name: "Dhar" },
//     { id: 17, name: "Dindori" },
//     { id: 18, name: "Guna" },
//     { id: 19, name: "Gwalior" },
//     { id: 20, name: "Harda" },
//     { id: 21, name: "Hoshangabad" },
//     { id: 22, name: "Indore" },
//     { id: 23, name: "Jabalpur" },
//     { id: 24, name: "Jhabua" },
//     { id: 25, name: "Katni" },
//     { id: 26, name: "Khandwa" },
//     { id: 27, name: "Khargone" },
//     { id: 28, name: "Mandla" },
//     { id: 29, name: "Mandsaur" },
//     { id: 30, name: "Morena" },
//     { id: 31, name: "Narsinghpur" },
//     { id: 32, name: "Neemuch" },
//     { id: 33, name: "Panna" },
//     { id: 34, name: "Raisen" },
//     { id: 35, name: "Rajgarh" },
//     { id: 36, name: "Ratlam" },
//     { id: 37, name: "Rewa" },
//     { id: 38, name: "Sagar" },
//     { id: 39, name: "Satna" },
//     { id: 40, name: "Sehore" },
//     { id: 41, name: "Seoni" },
//     { id: 42, name: "Shahdol" },
//     { id: 43, name: "Shajapur" },
//     { id: 44, name: "Sheopur" },
//     { id: 45, name: "Shivpuri" },
//     { id: 46, name: "Sidhi" },
//     { id: 47, name: "Singrauli" },
//     { id: 48, name: "Tikamgarh" },
//     { id: 49, name: "Ujjain" },
//     { id: 50, name: "Umaria" },
//     { id: 51, name: "Vidisha" }
//   ];

const districts = [
  { id: 1, name: "Dewas" },
  { id: 2, name: "Indore" },
  { id: 3, name: "Harda" },
  { id: 4, name: "Sehore" },
  { id: 5, name: "Narmadapuram" }, // Previously Hoshangabad
  { id: 6, name: "Betul" },
  { id: 7, name: "Khargone" },
  { id: 8, name: "Bhopal" },
  { id: 9, name: "Jabalpur" },
  { id: 10, name: "Gwalior" },
  { id: 11, name: "Ujjain" },
  { id: 12, name: "Sagar" },
  { id: 13, name: "Ratlam" },
];
  
  module.exports = districts;
  